export {MainPage} from './mainPage/ui/mainPage'
export {SocietyPage} from './societyPage/ui/SocietyPage'
export {DictionaryPage} from './dictionaryPage/ui/DictionaryPage'
export {GroupPage} from './groupPage/ui/GroupPage'
export {ModulePage} from './modulePage/ui/ModulePage'
export {TrainingPage} from './trainingPage/ui/TrainingPage'
export {AuthPage} from './authPage/ui/AuthPage'
// export {} from './'