export {MainPage} from './mainPage/ui/mainPage'
export {SocietyPage} from './societyPage/ui/SocietyPage'
export {DictionaryPage} from './dictionaryPage/ui/DictionaryPage'
export {GroupPage} from './groupPage/ui/GroupPage'
// export {} from './'
// export {} from './'